language: python

stages:
- linting
- test

python:
- '2.7'
- '3.7'
dist: xenial  # needed for 3.7+
env:
- TOXENV=py-test

jobs:
  include:
    - stage: linting
      name: check readme
      python: '3.6'
      env: TOXENV=check_readme
    - stage: test
      python: '2.7'
      env: SELFINSTALL=1
    - stage: test
      python: '3.6'
      env: SELFINSTALL=1

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pre-commit

install: pip install tox
script:
- python testing/runtests_travis.py
